#!/usr/bin/env bash
# installs nginx on webserver
# changes default webpage to print "Holberton School"
apt-get -y update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

#give user ownership to website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

#redirect to another page
sudo sed -i '24\        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# restarting nginx
sudo service nginx restart

echo "Done"



